### ISSUE TITLE
Can't compile in ubuntu 18.04

### ISSUE THREAD

**Issue by mrschaeffer2018** [madMAx43v3r/chia-plotter#483]
Hi i'm getting this error below, anyone have an idea what could it be? Thanks in advance.

/chia-plotter/src/chia_plot.cpp:16:10: fatal error: sodium.h: No such file or directory
 #include <sodium.h>
          ^~~~~~~~~~
compilation terminated.
CMakeFiles/chia_plot.dir/build.make:75: recipe for target 'CMakeFiles/chia_plot.dir/src/chia_plot.cpp.o' failed
make[2]: *** [CMakeFiles/chia_plot.dir/src/chia_plot.cpp.o] Error 1
CMakeFiles/Makefile2:449: recipe for target 'CMakeFiles/chia_plot.dir/all' failed
make[1]: *** [CMakeFiles/chia_plot.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable test_phase_3
[100%] Built target test_phase_3
[100%] Linking CXX executable test_phase_1
[100%] Built target test_phase_1
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by emosGambler** [comment]
Readme stands that the instruction is for Ubuntu 20.04. I am successfully using chia-plotter on 21.04.

What is the command that you are running and getting the error?

**Comment by madMAx43v3r** [comment]
`sudo apt install libsodium-dev`

**Comment by mrschaeffer2018** [comment]
> `sudo apt install libsodium-dev`

I have libsodium already installed, i read in reddit i have to make some modification in cmakefile. 

"I’ve made a few pull requests to the repo. You don’t need Xcode but so need /opt/homebrew on your cmake path. This can be done by editing the Cmakefile or putting it in your shell’s environment. This is true for both sodium and gmp.

**Comment by mrschaeffer2018** [comment]
> Readme stands that the instruction is for Ubuntu 20.04. I am successfully using chia-plotter on 21.04.
> 
> What is the command that you are running and getting the error?

I'm havinhg this error when trying to compile no binary is being build because of that.

**Comment by PSLLSP** [comment]
It is documented that it is not straight forward to compile madMAX at Ubuntu 18.04. Could be CMAKE build file modified to be compatible with older **cmake**??
It will be nice to have an option to build static binary, in that case I will be able to build madMAX at Ubuntu 20.04 and run binary at Ubuntu 18.04...

**Comment by madMAx43v3r** [comment]
cmake 3.14 requirement is because of chia code from bls-signatures, nothing I can do about it

**Comment by madMAx43v3r** [comment]
check bottom of readme how to install latest cmake on 18.04

**Comment by mrschaeffer2018** [comment]
I installed cmake 3.2 so is being used this newer version looks like this is not the problem is soemthing about libsodium wich is installed but sodium.h is not being seen in building process, do i have to point any path of the library libsodium when running the command of building? Maybe because my cmake 3.2 is locally installed on user folder but i update the path in bashrc and it should work i don't know the steps i should take to point the path of the library if this is the reason of the error.

**Comment by mrschaeffer2018** [comment]
I have also gcc 7.5.0 that impact in something? It should be a newer version?

**Comment by madMAx43v3r** [comment]
hmm I've managed to compile it on 18.04 just by installing latest cmake like this: https://askubuntu.com/questions/1203635/installing-latest-cmake-on-ubuntu-18-04-3-lts-run-via-wsl-openssl-error

**Comment by mrschaeffer2018** [comment]
But i installed cmake 3.2 when i run cmake --version it shows that cmake 3.2 is installed correctly.

**Comment by PSLLSP** [comment]
> But i installed cmake 3.2 when i run cmake --version it shows that cmake 3.2 is installed correctly.

I installed **cmake** manually to Ubuntu 18.04 (Linux Mint 19.3) and I was able to build madMax. I see something different, so I assume you installed wrong version of cmake.:

```
$ cmake --version
cmake version 3.20.4
```

```
$ which cmake
/usr/local/bin/cmake
```

```
$ ls /usr/local/share/cmake-3.20/
Help  include  Licenses  Modules  Templates
```

**cmake** can be get from here: https://cmake.org/download/
